import '@/styles/globals.css'
import Head from 'next/head'
import { Header,Footer } from '@/components'
import { favicon } from '@/public'
export default function App({ Component, pageProps }) {
  return (
    <div>
      <Head>
      <meta charSet="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta name="description" content="Generated by create next app" />
            <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors" />
            <meta name="generator" content="Hugo 0.80.0" />
            <title>Shoe Store</title>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link
                rel="preconnect"
                href="https://fonts.gstatic.com"
                crossOrigin="true"
            />
            <link
                href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
                rel="stylesheet"
            />
            <link rel="shortcut icon" href='/logo.svg'></link>
      </Head>
      <Header />
      <Component {...pageProps} />
      <Footer />
    </div>
  )
  
}
